version: 16.12.0.{build}
image: Visual Studio 2017

environment:
  STRIPE_TEST_SK: sk_test_eBgAzVoEpJKfYjD9nf2YoyMM

deploy:
- provider: NuGet
  api_key:
    secure: cmo/iFw1omV9CJBtyj3k2smUjb9KUSaYdL++rPTntmzyJ32gq76WeyYnojL5opzw
  on:
    branch: master

before_build:
  - ps: Write-Host $("`n               HOST INFORMATION               `n") -BackgroundColor DarkCyan
  - dotnet --info
  - ps: Write-Host $("`n               RESTORING PACKAGES FOR ALL FRAMEWORKS               `n") -BackgroundColor DarkCyan
  - dotnet restore src\

build:
  parallel: true

build_script:
  - ps: Write-Host $("`n               BUILDING EVERYTHING               `n") -BackgroundColor DarkCyan
  - dotnet build -c Release src\Stripe.net
  - dotnet build -c Debug src\Stripe.net
  - dotnet build src\Stripe.net.Tests -c Debug
  - dotnet build src\Stripe.Tests.Xunit -c Debug

after_build:
  - ps: Write-Host $("`n               PACKING UP               `n") -BackgroundColor DarkCyan
  - dotnet pack -c Release src\Stripe.net

test_script:
  - ps: Write-Host $("`n               RUNNING THE XUNIT TESTS               `n") -BackgroundColor DarkCyan
  - dotnet test src\Stripe.Tests.XUnit\Stripe.Tests.XUnit.csproj
  - ps: Write-Host $("`n               RUNNING THE MSPEC TESTS               `n") -BackgroundColor DarkCyan
  - dotnet test src\Stripe.net.Tests\Stripe.net.Tests.csproj /p:TargetFramework=net46

artifacts:
  - path: '**\*.nupkg'

# these commands tell appveyor to open an RDP session for debugging
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
